# 开启或停用模块
# true 为开启，false 为停用
OnOff:
  pre:
    verify_referrer.py: false
      # 简单防盗链预处理，开启后请修改下方相关配置

# 预处理安全相关
Security:
  # 防盗链相关设置
  onlyReferrer:
    type: ban
      # 策略类型
      # only: 仅允许 origin 中存在的 referrer
      # ban: 仅阻止 origin 中存在的 referrer

    origin:
      # 以下 Referrer 会被应用至上述规则
      - null
