app.core.biu:
  common:
    press_to_exit: "Press any key to exit..."
    success_to_login: "login successful"
  config:
    hint_port_is_in_use: "The port is occupied, please change the sys-host setting item in config.yml"
    hint_proxy_in_use: "Proxy is enabled"
    fail_to_load_config: "Failed to load the configuration file, PixivBiu cannot run properly"
  outdated:
    hint_latest: "Latest"
    hint_exist_new: "A new version is available"
    fail_to_check: "Failed to check for update"
    fail_to_check_duo_to_network: "Failed to check for update, probably because the server didn't respond for a long time"
    tell_to_download: "Visit https://biu.tls.moe/ to download"
    press_to_use_old: "Press any key to continue using this old version..."
  network:
    hint_in_check: "Checking network status..."
    fail_pixiv_and_use_bypass: "Cannot connect to Pixiv, enable bypassSNI route (may not be available temporarily)"
  loginHelper:
    hint_token_only: "Since Pixiv disables password login, you can only use Token to login for now"
    hint_before_start: "Network detection is about to start, this process can reduce the probability of not being able to use PixivBiu due to network problems"
    fail_to_get_token_due_to_network: "Your network is not working properly for Pixiv Token login, please adjust it and try again."
    fail_to_get_token_anyway: "There was an error getting the Token, please try again."
    fail_by_cloudflare_captcha: "Encountered Cloudflare protection when logging in, it may be caused by network environment issues. You can try to get the token again, or wait a while and log in again"
    is_need_to_get_token: "Continue? (y / n): "
  ready:
    hint_run: "Run"
    hint_how_to_use: "Enter the address into a modern browser"
    hint_version: "Version"
    hint_function_types: "Function Types"
    hint_image_service: "Image Service"
    hint_download_path: "Download Save Path"
    hint_program_path: "Program Directory"
    done_init: "Initialization completed"
  others:
    hint_in_update_token: "Trying to update token"

app.common.loginHelper:
  network:
    press_need_to_type_proxy: "Please enter the proxy listener address (can be blank): "
    hint_in_check: "Starting network detection..."
    hint_detect_proxy: "Proxy listener address (%s) detected, do you want to change it? (y / n): "
    is_need_to_type_proxy: "The system proxy address was not detected, do you need to set it manually? (y / n): "
  login:
    hint_intro_step_head: "[Login] Please follow these steps:"
    hint_intro_step_1: "1. Visit: %s?%s"
    hint_intro_step_2: "2. Open the browser's [Developer Tools / F12] and switch to the [Network] tab"
    hint_intro_step_3: "3. Turn on [Preserve log]"
    hint_intro_step_4: "4. Type [callback?] in the [Filter] input box"
    hint_intro_step_5: "5. Login to your Pixiv account"
    hint_intro_step_6: "6. After successfully logging in, there will be a message like [https://app-api.pixiv.net/...&code=...]"
    hint_intro_step_7: "7. Enter the parameter after [code] into this program"
    fail_code_918: "Code error. Please note that the program requires a different code each time it starts, and cannot reuse the previous one, and the Code doesn't contain quotation marks."
    fail_code_1508: "Code has expired. Please hurry up while doing the code fetching operation."
